/* ============================================================
   FM Navigate — Seed data
   Realistic founder/PM execution context
   ============================================================ */

const USERS = {
  vihan:   { id: 'vihan',   name: 'Vihan Mendis',   role: 'Product Manager', color: 'oklch(0.55 0.18 250)', initials: 'VM' },
  richard: { id: 'richard', name: 'Richard Cole',   role: 'Founder',         color: 'oklch(0.55 0.15 300)', initials: 'RC' },
  isuru:   { id: 'isuru',   name: 'Isuru Perera',   role: 'Eng Lead',        color: 'oklch(0.58 0.13 155)', initials: 'IP' },
};

const CATEGORIES = [
  'Product Development', 'Delivery', 'Technical', 'Compliance',
  'Sales', 'Marketing', 'Operations', 'Administration', 'Personal',
];

const STATUSES = ['Not Started', 'In Progress', 'Waiting', 'Blocked', 'Completed', 'Cancelled'];
const KANBAN_COLS = ['Not Started', 'In Progress', 'Waiting', 'Blocked', 'Completed'];
const PRIORITIES = ['Critical', 'High', 'Medium', 'Low'];

// "today" anchor for the prototype
const TODAY = new Date('2026-06-03T09:00:00');
const d = (offsetDays, h = 17) => {
  const x = new Date(TODAY);
  x.setDate(x.getDate() + offsetDays);
  x.setHours(h, 0, 0, 0);
  return x.toISOString();
};

let _id = 100;
const nid = () => `T-${++_id}`;

const SEED_TASKS = [
  {
    id: 'T-101',
    title: 'Sprint 58 planning with development team',
    description: `Need to prepare Sprint 58 planning with the development team. The pilot is scheduled for next week so this is critical. Need effort estimates from Isuru before finalizing the sprint. Target completion by Friday. Success means the sprint backlog is approved and communicated to the whole team.`,
    priority: 'Critical',
    category: 'Delivery',
    status: 'In Progress',
    dueDate: d(2),
    dependencies: ['Effort estimates from Isuru', 'Pilot scope sign-off'],
    successCriteria: 'Sprint 58 backlog approved by Richard and communicated to the dev team.',
    risk: 'Pilot timing leaves no slack — slip here cascades into the pilot.',
    effort: 'M',
    ownerId: 'vihan',
    progress: 60,
    createdAt: d(-4), updatedAt: d(0, 8), completedAt: null,
    comments: [
      { id: 'c1', userId: 'vihan', comment: 'Draft backlog ready. Waiting on Isuru for capacity numbers.', createdAt: d(-1, 16) },
      { id: 'c2', userId: 'richard', comment: 'Make sure the onboarding flow stays in scope for the pilot.', createdAt: d(0, 8) },
    ],
    progressLog: [
      { id: 'pl1', percent: 30, note: 'Drafted the backlog skeleton and pulled last sprint carryover.', link: '', fileName: '', fileData: '', userId: 'vihan', at: d(-2, 11) },
      { id: 'pl2', percent: 60, note: 'Prioritised stories with the team; awaiting capacity numbers from Isuru.', link: 'https://example.com/sprint58-board', fileName: '', fileData: '', userId: 'vihan', at: d(-1, 16) },
    ],
    activity: [
      { type: 'created', userId: 'vihan', at: d(-4) },
      { type: 'status', userId: 'vihan', at: d(-2), detail: 'Not Started → In Progress' },
      { type: 'progress', userId: 'vihan', at: d(-2, 11), detail: '30%' },
      { type: 'progress', userId: 'vihan', at: d(-1, 16), detail: '60%' },
      { type: 'comment', userId: 'vihan', at: d(-1, 16) },
    ],
  },
  {
    id: 'T-102',
    title: 'Pilot environment preparation for ACME Logistics',
    description: `Prepare a dedicated pilot environment for ACME Logistics ahead of next week's kickoff. Includes seeded demo data, SSO config, and a walkthrough script. High priority — first paying-adjacent pilot.`,
    priority: 'Critical',
    category: 'Product Development',
    status: 'In Progress',
    dueDate: d(4),
    dependencies: ['Sprint 58 planning'],
    successCriteria: 'Pilot tenant live with seeded data, SSO working, walkthrough rehearsed once.',
    risk: 'SSO with ACME IdP is unproven; could need a day of debugging.',
    effort: 'L',
    ownerId: 'vihan',
    progress: 35,
    createdAt: d(-6), updatedAt: d(-1, 11), completedAt: null,
    comments: [
      { id: 'c3', userId: 'vihan', comment: 'Tenant provisioned. SSO metadata requested from ACME IT.', createdAt: d(-1, 11) },
    ],
    activity: [
      { type: 'created', userId: 'vihan', at: d(-6) },
      { type: 'status', userId: 'vihan', at: d(-3), detail: 'Not Started → In Progress' },
    ],
  },
  {
    id: 'T-103',
    title: 'Investor update pack — Q2 traction',
    description: `Compile the Q2 investor update: traction metrics, pipeline, runway, and pilot status. Richard presents to the board on the 12th. Needs financial data from finance before charts can be built.`,
    priority: 'High',
    category: 'Administration',
    status: 'Waiting',
    dueDate: d(6),
    dependencies: ['Q2 financial close from finance'],
    successCriteria: 'Board-ready deck with verified metrics, reviewed by Richard.',
    risk: 'Financial close is the bottleneck — finance has not committed a date.',
    effort: 'M',
    ownerId: 'vihan',
    progress: 40,
    createdAt: d(-5), updatedAt: d(-1, 14), completedAt: null,
    comments: [
      { id: 'c4', userId: 'richard', comment: 'I want the pilot narrative front and center this quarter.', createdAt: d(-2, 9) },
    ],
    activity: [
      { type: 'created', userId: 'vihan', at: d(-5) },
      { type: 'status', userId: 'vihan', at: d(-1, 14), detail: 'In Progress → Waiting' },
    ],
  },
  {
    id: 'T-104',
    title: 'Awaiting Q2 financial data from finance',
    description: `Blocked on the Q2 financial close. Needed for the investor pack and runway projection. Escalate if not received by Thursday.`,
    priority: 'High',
    category: 'Compliance',
    status: 'Blocked',
    dueDate: d(1),
    dependencies: ['Finance Q2 close'],
    successCriteria: 'Verified Q2 P&L and cash position received.',
    risk: 'Directly blocks the investor pack; board date is fixed.',
    effort: 'S',
    ownerId: 'vihan',
    progress: 10,
    createdAt: d(-7), updatedAt: d(-2, 10), completedAt: null,
    comments: [
      { id: 'c5', userId: 'vihan', comment: 'Pinged finance twice. No committed date yet — flagging for Richard.', createdAt: d(-2, 10) },
    ],
    activity: [
      { type: 'created', userId: 'vihan', at: d(-7) },
      { type: 'status', userId: 'vihan', at: d(-4), detail: 'Waiting → Blocked' },
      { type: 'comment', userId: 'vihan', at: d(-2, 10) },
    ],
  },
  {
    id: 'T-105',
    title: 'SOC 2 readiness — access control policy',
    description: `Draft and circulate the access control policy as part of SOC 2 Type I readiness. Compliance auditor wants documented policies before fieldwork begins.`,
    priority: 'Medium',
    category: 'Compliance',
    status: 'In Progress',
    dueDate: d(9),
    dependencies: [],
    successCriteria: 'Access control policy drafted, reviewed, and version-controlled.',
    risk: 'Audit scope may expand if RBAC implementation lags policy.',
    effort: 'M',
    ownerId: 'vihan',
    progress: 45,
    createdAt: d(-9), updatedAt: d(-1, 15), completedAt: null,
    comments: [],
    activity: [
      { type: 'created', userId: 'vihan', at: d(-9) },
      { type: 'status', userId: 'vihan', at: d(-6), detail: 'Not Started → In Progress' },
    ],
  },
  {
    id: 'T-106',
    title: 'Product demo for prospective design partner',
    description: `Run a live product demo for a prospective design partner in fintech. Tailor the script to their compliance use case. Scheduled for next Wednesday.`,
    priority: 'High',
    category: 'Sales',
    status: 'Not Started',
    dueDate: d(7),
    dependencies: ['Pilot environment preparation'],
    successCriteria: 'Demo delivered; follow-up meeting booked.',
    risk: 'Reuses pilot env — if pilot prep slips, demo has no environment.',
    effort: 'S',
    ownerId: 'vihan',
    progress: 0,
    createdAt: d(-2), updatedAt: d(-2), completedAt: null,
    comments: [],
    activity: [{ type: 'created', userId: 'vihan', at: d(-2) }],
  },
  {
    id: 'T-107',
    title: 'Onboarding flow redesign — first-run experience',
    description: `Redesign the first-run onboarding so a new user reaches their first task within two minutes. Part of pilot readiness. Medium priority but high leverage for activation.`,
    priority: 'Medium',
    category: 'Product Development',
    status: 'In Progress',
    dueDate: d(5),
    dependencies: [],
    successCriteria: 'New users reach first meaningful action in under 2 minutes in testing.',
    risk: 'Scope creep into full settings redesign.',
    effort: 'M',
    ownerId: 'vihan',
    progress: 55,
    createdAt: d(-8), updatedAt: d(0, 9), completedAt: null,
    comments: [
      { id: 'c6', userId: 'vihan', comment: 'Two of three steps prototyped. Usability check Thursday.', createdAt: d(0, 9) },
    ],
    activity: [
      { type: 'created', userId: 'vihan', at: d(-8) },
      { type: 'status', userId: 'vihan', at: d(-5), detail: 'Not Started → In Progress' },
    ],
  },
  {
    id: 'T-108',
    title: 'Website launch copy + pricing page',
    description: `Finalize launch marketing copy and the pricing page. Waiting on positioning sign-off from Richard before publishing.`,
    priority: 'Medium',
    category: 'Marketing',
    status: 'Waiting',
    dueDate: d(8),
    dependencies: ['Positioning sign-off from Richard'],
    successCriteria: 'Pricing page and launch copy approved and staged.',
    risk: 'Positioning still in flux pending pilot learnings.',
    effort: 'S',
    ownerId: 'vihan',
    progress: 70,
    createdAt: d(-10), updatedAt: d(-3, 13), completedAt: null,
    comments: [],
    activity: [
      { type: 'created', userId: 'vihan', at: d(-10) },
      { type: 'status', userId: 'vihan', at: d(-3, 13), detail: 'In Progress → Waiting' },
    ],
  },
  {
    id: 'T-109',
    title: 'Hire contract QA engineer for pilot',
    description: `Bring on a contract QA engineer to harden the product before the pilot. Operations task — screen, interview, and onboard within two weeks.`,
    priority: 'Low',
    category: 'Operations',
    status: 'Not Started',
    dueDate: d(12),
    dependencies: [],
    successCriteria: 'QA contractor signed and onboarded to the codebase.',
    risk: 'Short timeline; candidate pool is thin.',
    effort: 'M',
    ownerId: 'vihan',
    progress: 0,
    createdAt: d(-1), updatedAt: d(-1), completedAt: null,
    comments: [],
    activity: [{ type: 'created', userId: 'vihan', at: d(-1) }],
  },
  {
    id: 'T-110',
    title: 'API rate-limiting + abuse protection',
    description: `Implement rate limiting and basic abuse protection on the public API before exposing it to the pilot tenant. Technical hardening.`,
    priority: 'High',
    category: 'Technical',
    status: 'Blocked',
    dueDate: d(3),
    dependencies: ['Infra access from Isuru'],
    successCriteria: 'Per-tenant rate limits enforced; load test passes.',
    risk: 'Blocked on infra access; Isuru is heads-down on the pilot build.',
    effort: 'M',
    ownerId: 'vihan',
    progress: 20,
    createdAt: d(-6), updatedAt: d(-2, 12), completedAt: null,
    comments: [
      { id: 'c7', userId: 'vihan', comment: 'Need gateway credentials from Isuru to proceed.', createdAt: d(-2, 12) },
    ],
    activity: [
      { type: 'created', userId: 'vihan', at: d(-6) },
      { type: 'status', userId: 'vihan', at: d(-2, 12), detail: 'In Progress → Blocked' },
    ],
  },
  // completed this week
  {
    id: 'T-111',
    title: 'User management UI',
    description: `Ship the user management screen: invite, role assignment, and deactivation. Needed before the pilot so ACME can manage their own users.`,
    priority: 'High',
    category: 'Product Development',
    status: 'Completed',
    dueDate: d(-1),
    dependencies: [],
    successCriteria: 'Admins can invite, assign roles, and deactivate users.',
    risk: '',
    effort: 'M',
    ownerId: 'vihan',
    progress: 100,
    createdAt: d(-12), updatedAt: d(-1, 12), completedAt: d(-1, 12),
    comments: [],
    activity: [
      { type: 'created', userId: 'vihan', at: d(-12) },
      { type: 'completed', userId: 'vihan', at: d(-1, 12) },
    ],
  },
  {
    id: 'T-112',
    title: 'Demo environment setup',
    description: `Stand up a reusable demo environment with realistic seed data for sales and partner demos.`,
    priority: 'Medium',
    category: 'Delivery',
    status: 'Completed',
    dueDate: d(-2),
    dependencies: [],
    successCriteria: 'Demo tenant reproducible from a script in under 10 minutes.',
    risk: '',
    effort: 'S',
    ownerId: 'vihan',
    progress: 100,
    createdAt: d(-9), updatedAt: d(-2, 15), completedAt: d(-2, 15),
    comments: [],
    activity: [
      { type: 'created', userId: 'vihan', at: d(-9) },
      { type: 'completed', userId: 'vihan', at: d(-2, 15) },
    ],
  },
  {
    id: 'T-113',
    title: 'Fix billing webhook retries',
    description: `Billing webhooks were dropping on transient failures. Added idempotent retries with backoff.`,
    priority: 'Medium',
    category: 'Technical',
    status: 'Completed',
    dueDate: d(-3),
    dependencies: [],
    successCriteria: 'No dropped webhooks under simulated failure; retries verified.',
    risk: '',
    effort: 'S',
    ownerId: 'vihan',
    progress: 100,
    createdAt: d(-7), updatedAt: d(-3, 11), completedAt: d(-3, 11),
    comments: [],
    activity: [
      { type: 'created', userId: 'vihan', at: d(-7) },
      { type: 'completed', userId: 'vihan', at: d(-3, 11) },
    ],
  },
  {
    id: 'T-114',
    title: 'Board meeting logistics + agenda',
    description: `Coordinate logistics and circulate the agenda for the June 12 board meeting.`,
    priority: 'Low',
    category: 'Administration',
    status: 'Completed',
    dueDate: d(-1),
    dependencies: [],
    successCriteria: 'Agenda circulated; room and dial-in confirmed.',
    risk: '',
    effort: 'S',
    ownerId: 'vihan',
    progress: 100,
    createdAt: d(-5), updatedAt: d(-1, 9), completedAt: d(-1, 9),
    comments: [],
    activity: [
      { type: 'created', userId: 'vihan', at: d(-5) },
      { type: 'completed', userId: 'vihan', at: d(-1, 9) },
    ],
  },
  {
    id: 'T-115',
    title: 'Renew domain + SSL certificates',
    description: `Annual renewal of primary domain and wildcard SSL certificate. Cancelled — moved to managed certs via the platform.`,
    priority: 'Low',
    category: 'Operations',
    status: 'Cancelled',
    dueDate: d(-2),
    dependencies: [],
    successCriteria: '',
    risk: '',
    effort: 'S',
    ownerId: 'vihan',
    progress: 0,
    createdAt: d(-6), updatedAt: d(-3, 10), completedAt: null,
    comments: [
      { id: 'c8', userId: 'vihan', comment: 'Superseded by managed certificates. Closing.', createdAt: d(-3, 10) },
    ],
    activity: [
      { type: 'created', userId: 'vihan', at: d(-6) },
      { type: 'status', userId: 'vihan', at: d(-3, 10), detail: 'Not Started → Cancelled' },
    ],
  },
];

Object.assign(window, {
  USERS, CATEGORIES, STATUSES, KANBAN_COLS, PRIORITIES,
  SEED_TASKS, TODAY, nid,
});
